/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package williamhenry.school;


import javax.swing.*;
import java.awt.event.*;
import java.awt.BorderLayout;
import java.awt.Color;

/**
 *
 * @author sysop
 */
public class Test2JFrame extends JFrame {

    /**
     * Creates new form Test2JFrame
     */
    public Test2JFrame() {
        setSize(400,400);
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
	setTitle("School Management System - Add Student");
		
	// setLayout(new BorderLayout());
	initTopPanel();
        initMiddlePanel();
        initBottomPanel();	
	
        pack();

        setVisible(true);
        // initComponents();
        
    }

    
    // Topmost red panel.
	private void initTopPanel() {
		// Create the JPanel
		JPanel topPanel = new JPanel();

		// Set the JPanel's layout manager to a BorderLayout
		topPanel.setLayout(new BorderLayout());

		// Set the JPanel's background to red
		topPanel.setBackground(Color.red);

		// Add this JPanel to the northern region of our main window
		add(topPanel, BorderLayout.NORTH);
                topPanel.add(new JLabel("Add/Edit Student"), BorderLayout.PAGE_START);

        }

	// Center white panel
	private void initMiddlePanel() {
		// Create the JPanel
		JPanel middlePanel = new JPanel();

		// Set the JPanel's layout manager to a BorderLayout
		middlePanel.setLayout(new BorderLayout());

		// Set the JPanel's background to white
		middlePanel.setBackground(Color.white);

		// Add this JPanel to the center region of our main window
		add(middlePanel, BorderLayout.CENTER);
	}

	// Bottom blue panel
	private void initBottomPanel() {
		// Create the JPanel
		JPanel bottomPanel = new JPanel();

		// Set the JPanel's layout manager to a BorderLayout
		bottomPanel.setLayout(new BorderLayout());

		// Set the JPanel's background to blue
		bottomPanel.setBackground(Color.blue);

		// Add this JPanel to the center region of our main window
                add(bottomPanel, BorderLayout.SOUTH);
                
                JButton buttonS = new JButton("Save");
                JButton buttonE = new JButton("Exit");
                GroupLayout layout = new GroupLayout(bottomPanel);
		//bottomPanel.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                            .addGap(99, 99, 99)
                            .addComponent(buttonS)
                            .addGap(99, 99, 99)
                            .addComponent(buttonE))
                            //.addGap(168, 168, 168))
                        );
                // JButton buttonS = new JButton("Save");
                // bottomPanel.add(buttons, BorderLayout.LINE_START);
        
                // button = new JButton("Exit");
                // bottomPanel.add(button, BorderLayout.LINE_END);
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Test2JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Test2JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Test2JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Test2JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Test2JFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
